### ISSUE TITLE
Implement a validator

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-tabby#10]
It should take a record (collection of tables), and check them for compliance with the spec, and with the specs defined in the metadata record itself.

It should also report whether a datalad dataset can be generated from that record reproducibly.

**Comment by mih** [comment]
Following an adoption of https://github.com/psychoinformatics-de/datalad-tabby/issues/12 we would need to implement the following:

- be able to export `tabby` context/format/term/syntax specifications to a schema (or a set of)
- convert the tabular information into a standardized (JSON(-LD)) representation

**Comment by mih** [comment]
The behavior of the validator must match the parsing semantics of the metadata spec definitions: single-pass vs 2-pass.

**Comment by jsheunis** [comment]
What I have in mind is autocreating a JSONschema-based schema from any tabby document (and having the default readily available). This would mean that each tabby document would have to be parsed first and output into a JSON doc, and then validated.

Or does it make more sense to have a validator that validates a tabby document line for line (and afterwards as a whole) in the native format?

**Comment by mih** [comment]
Was wondering the same thing. It would make sense for error reporting, I think.

**Comment by christian-monch** [comment]
For coordination. I have started with a validator, that follows the spec in #12

**Comment by mih** [comment]
Right now, I do not see a way to implement a validator without something like https://www.w3.org/TR/shacl/

Such a validator, however, would be for a specific application rather than the concept of a `tabby` record in general.

I am closing this issue for now. Feel free to reopen with a concrete plan on how to approach a validator implementation.
