### ISSUE TITLE
Metadata properties for reproducible dataset generation

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-tabby#11]
A `tabby` metadata record describes a single dataset version. This means that in order to generate a datalad dataset reproducibly, we need all information necessary to produce the exact same commit all the time.

Key information that goes into a commit (gitsha):

- prior commit/state
- agent information (author/committer)
- timestamp
- content info of all files

We need to precisely define all items above from metadata elements.

- *prior commit/state*: we only describe a single version so there is nothing to do. If multi-version datalad datasets were to be generated, they would need multiple metadata records fulfilling all other requirements to yield reproducible outcomes. It might make sense to support something like `wasDerivedFrom` (with the identifier of a previous version as value) to declare version history in metadata. Alternatively, a version order would need to be declared on dataset generation. Typically such version metadata records would be kept in some system/database that likely already has means to declare versions, and a dedicated field would/could be redundant.
- *agent information*: We need one or two entities (author vs committer). author could be the first `author` declared in the record, or alternative we introduce a `curator` field to use as `committer`. We could also join the names of all authors and use a dedicated contact email as email address. But this is likely messy.
- *timestamp*: either we have content/file records that declare "last-modified" (and we select the latest timestamp -- which would require them to be valid, with a known format), or we require a dedicated timestamp field (https://schema.org/dateModified seem appropriate for that; and  ISO 8601 a good format)
- *content info*: we need a name, hash and size for any file in a dataset

**Comment by christian-monch** [comment]
W.r.t. content info: I think we might need type information of a file as well

**Comment by mih** [comment]
> W.r.t. content info: I think we might need type information of a file as well

Can you give an example what kind of information would be needed and what it would be needed for?

**Comment by christian-monch** [comment]
I am refering to `file` vs `executable`. I don't have a concrete example, but if we want to be able to describe an existing dataset with a `tabby` metadata record, this would be an aspect that should be represented.

**Comment by mih** [comment]
Thanks. Let's refer to it then as file `mode`, and not `type` to distinguish from things like `text/html` -- which would be a more immediate association from some people.

That being said, `mode` is only relevant for reproducing a **DataLad** dataset  (via a tabby record) as a DataLad dataset.

It is not relevant for producing the exact same DataLad dataset **from a tabby record** twice (it would simply treat any file as just that, if not told otherwise).

In the case where we have a **DataLad dataset** as a starting point, we have all DataLad tooling at our disposal, and we can provide a rich description that also includes `mode` at very little cost.

This issue, however, is about the bare necessities to turn a tabby record into a Git repo, and get the same outcome when done twice.

**Comment by christian-monch** [comment]
I agree, for equivalent results, the type is not necessary.

**Comment by mih** [comment]
I think we can close this information issue now.
