### ISSUE TITLE
Define procedure from "tabby" to "JSON-LD"

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-tabby#15]
Roughly speaking:

- tabby is nothing but JSON-LD  with constraints on the (JSON) structure, but no constraints on the semantics
- tabby's tabular components can represent a JSON object, or an array of homogeneous JSON objects
- tabby's native format is a (#16) collection of plain-text files (TSV, JSON)

The procedure for converting a tabby document to JSON-LD is:

- all TSV tables comprising a document are read in their tabular form
- a dependency graph of these tables is constructed (see #17 for how dependencies/imports are declared), and tables are processed sequentially, starting from leaf-nodes in the dependency graph (i.e., tables that do not import others)
- processing converts the information represented in the table into a JSON-LD document. After processing, any dependency/import declarations are resolved by insert the JSON-LD document verbatim at the import location

For each table with no unresolved imports the following procedure is applied:

- tabular representation is converted to JSON (see https://github.com/psychoinformatics-de/datalad-tabby/issues/12#issuecomment-1611043484 for details)
  - "horizontal" tables represent key/value pairs of a JSON objects, where multi-column values are represented as a JSON array of basic data types
  - "vertical" tables represent an array of JSON objects, where keys are given in the header row and values are given in any other row, with one JSON-object per row
- once the JSON form is constructed, a context is inserted under a `@context` key, to create a JSON-LD document. The context is either read from a table-specific side-car file (see #16), or a default, implementation-provided context is used
- once the JSON-LD document is complete, it is subjected to JSON-LD framing to create the final JSON-LD document

**Comment by jsheunis** [comment]
This logical flow makes sense to me, and the separation of steps allow for self-contained pieces of code that also address other goals, e.g. https://github.com/psychoinformatics-de/datalad-tabby/issues/19

**Comment by jsheunis** [comment]
One thing that I don't fully grasp yet is the relation between: 1) constructing a dependency graph between tables, and 2) subjecting the resulting JSON-LD document (after resolving dependencies, applying context, etc) to framing. IIUC, the framing document could provide a specification of standard relationships between properties that will allow a flat list of objects to be nested according to these relationships during framing. Would these relationships be the same as, similar to, or orthogonal to the relationships introduced in the data via the importing of one or more tables into another?

**Comment by christian-monch** [comment]
FMPOV, the include-syntax mainly allows to define nested objects. In a addition, it allows to re-use them in the referencing files.

Conceptually, the top-level document will contain a set of object definitions in which the values are possibly other objects or a list (the use of includes is just one "syntactic" way of representing nesting. We could also have used key names like "author.name" to indicate that "author" is an object with a property called "name", or "authors[0].name"  to indicate that "authors" is a list of objects and that the first object in the list has a property called "name").

When the content is handed as input to framing, the include-relation is not visible anymore. Only the containment-relations of the JSON-objects are present. So I would say, that the content of the framing document is independent of the include-relations.

(The framing doc is to some degree influenced by the structure of the JSON-objects, because the "match"-expressions in the framing document must match the type-names and object hierarchies of the JSON objects.)

**Comment by mih** [comment]
> When the content is handed as input to framing, the include-relation is not visible anymore. 

Still thinking about that. This is what I had in mind. However, it would mean that there cannot be an intermediate conversion to JSON (TSV -> JSON -> JSON-LD). Everthing will be JSON-LD.

This is ultimately sensible, but also implies all the costs of -LD data handling unconditionally on-read.

**Comment by mih** [comment]
Update: motivated by the desired to avoid semantic-data processing as long as anyhow possible.

```py
def load_tabby(fpath: Path, single: bool, jsonld: bool) -> Dict | List
    ...
```

To load a `tabby` record, we call `load_tabby` with the path to the `dataset` sheet, and `single=True`.

`load_tabby()` parses the filename to determine the tabby-name (prefix).

- with `single=True`, `load_tabby()`:
  - returns a `dict`
  - reads the table row-by-row, the first column defines the key for the corresponding dict item
  - if more than one value-column is used, all values are collated into an a list, which becomes the dict item's value
  - if a single value-column is used:
    - if the value is not a string that starts with `@tabby-`, it is used as the dict item's value
    - else `load_tabby()` is called with a file path corresponding to the sheet name, and `single=True|False` depending on whether the statement is `@tabby-single-...` or `@tabby-many-...`, and the return value is used as the dict item's value
  - if `jsonld=True`
    - if there is a corresponding frame file for the sheet:
      - if there is a corresponding context file for the sheet, load and assigned to  `@context`
      - apply the frame
    - elif  there is a corresponding context file for the sheet, load and assigned to  `@context`
  - return the `dict`
- with `single=False`, `load_tabby()`:
  - returns a `list`
  - read the header row
  - reads the table row-by-row, each column defines the value corresponding to a key given by the header row, jointly forming the items in a `dict` that represents that row
  - any column value that starts with `@tabby-` causes `load_tabby()` to be called recursively as described above, the return value providing the column value
  - the resulting dict for each row is appended to the returned `list`


This procedure makes it possible to perform a `load` while keeping the JSON-LD processing aspect optional, unless it is required for framing.
