### ISSUE TITLE
Native file-format and naming specification

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-tabby#16]
In its native/archival form, tabby is a collection of plain text files. The bulk of the information is encoded in tables. Each table has an associated JSON-LD context definition (https://www.w3.org/TR/json-ld11/#the-context), and an associated JSON-LD frame (https://www.w3.org/TR/json-ld11-framing/#dfn-framing). Both context and frame are optional, and implementation-provided defaults take their place if undefined.

Any table is represented as a plain-text, tab-separated values (TSV) file -- utf-8 encoded.

Any JSON-LD file is a JSON-LD v1.1 compliant document.

The following naming convention is used to associate all files with a particular metadata record.

- metadata table: `<dataset-id>_<table-name>.tsv`
- table context: `<dataset-id>_<table-name>.ctx.jsonld`
- table frame: `<dataset-id>_<table-name>.frame.jsonld`

where

- `<dataset-id>` is an identifier for the described dataset that is identical across all files comprising a single metadata record. This ID is an arbitrary, case-sensitive string. For compatibility reasons it is recommended to limit the identifier to ASCII values, and possibly alpha-numeric characters.
- `<table-name>` is a unique name for a particular table component of a metadata record, used to associated values, context, and frame for that component to each other. The name must be lower-case and only consist of the character set `[a-z0-9-]`.
- each metadata record must have a table named `dataset`.

A minimal, complete record can take the form of a single file:

- `penguins_dataset.tsv`

A detailed record may look like:

- `penguins_dataset.tsv`
- `penguins_authors.tsv`
- `penguins_authors.ctx.jsonld`
- `penguins_funders.tsv`
- `penguins_funders.frame.jsonld`
- `penguins_image-files.tsv`
- `penguins_image-files.ctx.jsonld`
- `penguins_image-files.frame.jsonld`

Notes on possible practices:

- tabby records on many datasets can be put into a single directory. They can be discovered via the glob `*_dataset.tsv`
- given a `*_dataset.tsv` filename, the `<dataset-id>` is determined as the prefix string to `_dataset.tsv`. All files comprising the full record can then be located via the glob `<dataset-id>_*.{tsv,ctx.jsonld,frame.jsonld}`

**Comment by mslw** [comment]
Would it make sense to require the dataset file to be named `*_dataset.tabby.tsv` instead of `*_dataset.tsv` to further distinguish it from "regular" (i.e non-tabby) tsv files? Other extensions could remain unchanged.

**Comment by mih** [comment]
What distinguishes a tabby from a non-tabby TSV?

**Comment by mslw** [comment]
> What distinguishes a tabby from a non-tabby TSV?

Purpose (tabby is used to declare a dataset and its metadata, non-tabby is any kind of data in tabular format), and semantics (tabby assigns specific meaning to rows / columns).

I am thinking of a situation where tabby files are placed inside a data folder or dataset (alongside data), and used to represent a non-datalad subdataset - is this still a valid use case? In this situation you are more likely to have a name collision with, say `gentoo_dataset.tsv` used to store actual data (on bill and flipper lengths). Our code would then have to realize from the semantics that this is not a description of a dataset.

Does it make sense?

**Comment by mih** [comment]
I see the high-level conflict potential, but I do not yet see it happening in any real-world usage.

I think it all hinges on "Our code would then have to realize from the semantics that this is not a description of a dataset" -- I do not think that is the case.

When `gentoo_dataset.tsv` is given as an argument to `load_tabby()` (see #35), a users declares this to be a tabby record. Then and only then, it is interpreted as such. In any other case, it is just a TSV file.

In the context of `load_tabby()`, `*_<somename>.tsv` files are not randomly read and interpreted. Instead they have to be specifically imported in other TSV files via `@tabby-...` statements.

The only "conflict" that actually exists is that `tabby2xlsx()` does not use `load_tabby()` to determine linked TSV files. Instead it globs for `<prefix>_*.tsv`, and therefore might put too many sheets into an XSLX file. However, this is inconvenient more than an actual conflict.

That being said, I would be comfortable to simply declare "throw-on-a-pile" file organization approaches to not be advisable ;-)

**Comment by mslw** [comment]
Thanks for clarifying - I think we're good now.

I admit that I was thinking of discovery procedures (dataset metadata extractors maybe). I agree that having name as an input (to whatever procedure) removes any ambiguity.
