### ISSUE TITLE
Define "import" syntax for TSV files

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-tabby#17]
In order to declare the desired document nesting structure for a tabby record, we need a syntax to declare that the information in a particular TSV table is to be "imported" in a specific place.

Tables are identified by a unique name/label within the scope of a tabby record (#16)

The syntax must enable reliable detection and avoid conflict with any other syntax or semantics.

We could use `@tabby-<table-name>` as a cell value.

The following row in a `_dataset.tsv` file would then declare that the information in `_authors.tsv` relates to the dataset via the `author` property:

```tsv
"author", "@tabby-authors"
```

Note that table name and relationship label are different. There is no implicit semantic relationship between the `author` property and the `authors` table name.

**Comment by mih** [comment]
After  the exploration in #22, I think we need to have two import statements. Following the concept in the top-post, we should/would have

- `@tabby-obj-<name>`
- `@tabby-objs-<name>`

The first one include the description of a single object (horizontal table), and the second deals with many homogeneous objects (vertical table format).

This keeps the filenames of the tables simple and free from here-is-how-you-should-use-me semantics, and also the table content similarly agnostic of this use case.

This should not be a problem for a parser. We already have the `dataset` record as the one starting point for discovery. We can also discover the anticipated structure of the information from the content of that record. And we can have a set of conventions on inclusions (as described above) that simply use these two formats.

**Comment by mih** [comment]
Still not happy with

- `@tabby-obj-<name>`
- `@tabby-objs-<name>`

it requires to much hidden knowledge to make sense. What about

- `@tabby-single-<name>`
- `@tabby-many-<name>`

**Comment by jsheunis** [comment]
I followed the arguments and I'm happy with the latest suggestion.

**Comment by christian-monch** [comment]
I like the latest suggestion as well.

One question, can we use import-statements in vertical tables? I don't see why not, and I think we should, for example for a list of authors. Just wanted to ask to make sure.

**Comment by christian-monch** [comment]
One question: can we use import-statements in vertical tables? I don't see why not, and I think we should, for example for a list of authors. Just wanted to ask to make sure.

**Comment by christian-monch** [comment]
The example might be a little bit constructed, maybe we find a more relevant use case (comma-separated):
```
Authors,                Journal,    Title
@tabby-single-joe,      Cell,       Flying cells
@tabby-many-group5,     Nature,     Red water
```

**Comment by mih** [comment]
I think that is a valid example. Not something I see being part of a default template, but it should be supported.
