### ISSUE TITLE
Alter template/example to capture a data-controller entity

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-tabby#18]
Right now we have a generic `contact` and authors. But in most cases we need to know who is legally responsible for some data, and can be contacted regarding any "governance" aspects (granting access, etc.)

Likely, this will need to be its own `datalad-controller` table with `name`, `email`, and possibly `address` fields -- whatever is needed from a legal compliance POV.

See #24

It would make sense to associate a data controller as https://schema.org/accountablePerson with a dataset.

**Comment by jsheunis** [comment]
Seems like this is superseded by https://github.com/psychoinformatics-de/datalad-tabby/issues/29 and can be closed?

**Comment by mih** [comment]
Yes, closing. The docs at https://rdm.sfb1451.de/data-catalog-submission/#table-data-controller-required go even beyond that.
