### ISSUE TITLE
Implement metadata extractor

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-tabby#2]
Scope: convert the TSV files into a defined JSON(-LD) data structure

**Comment by jsheunis** [comment]
The user docs for creating an extractor: https://docs.datalad.org/projects/metalad/en/latest/user_guide/writing-extractors.html

**Comment by jsheunis** [comment]
Relevant work that has already been done:
- Standalone conversion script: https://github.com/psychoinformatics-de/catalog-utilities/blob/tsv-to-catalogjson/bin/tubby2catalog

**Comment by jsheunis** [comment]
I started thinking about extractor implementation, and one of the first things to define in the extractor is where to locate the metadata source files. This is currently done in a per-extractor approach, leading to code duplication. I suggested bringing standard helper functionality into metalad: https://github.com/datalad/datalad-metalad/issues/379
