### ISSUE TITLE
Provide guidelines on "what is a single dataset" i.e. scope of a metadata record

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-tabby#25]
This relates to the technical questions related to splitting DataLad datasets, but also includes aspects of description/metadata. For example, it makes a lot of sense to not lump together components of a larger dataset that are governed by different entities and rules (e.g., personal data vs technical information; collection of acquisitions provided by different legal entities). Describing homogeneous components is more straightforward than complex mixtures (think GDPR data controllers, authors, ...).

**Comment by jsheunis** [comment]
Things that I think would make sense to mention in such guidelines:
- a dataset is a collection of files, usually grouped together by a commonality such as acquisition method, purpose of use, file type, etc
- the concepts of dataset linking and nesting, and reasons for doing this (e.g. in the context of datalad: https://handbook.datalad.org/en/latest/basics/101-106-nesting.html, https://handbook.datalad.org/en/latest/basics/101-127-yoda.html#p1 i.e. "one thing, one dataset"). "One thing" could be:
   - input or output dataset
   - code vs raw data
   - personal vs non-personal data
   - data from one project of a consortium or lab
- clarify the differences between a dataset and versions of a dataset (is `palmerpenguins` a single dataset, or is `palmerpenguins_v0.1.4` a single dataset). related: https://github.com/psychoinformatics-de/datalad-tabby/issues/56

**Comment by mih** [comment]
This issue is now tracked as one aspect of dataset descriptions with `tabby` in https://github.com/psychoinformatics-de/datalad-tabby/issues/102
