### ISSUE TITLE
Useful/default ontologies/namespaces to add in default context

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-tabby#26]
If we define some upfront, we help limit the proliferation of terms/defs.

- [x] `schema`: https://schema.org/
- [x] `uom`: http://www.ontology-of-units-of-measure.org/resource/om-2/
- [ ] `dcmterms`: https://www.dublincore.org/specifications/dublin-core/dcmi-terms/
- [ ] `irao`: http://ontology.ethereal.cz/irao
- [ ] `gconsent`: https://w3id.org/GConsent (see #24)
- [ ] `DUO`: https://github.com/EBISPOT/DUO
- [ ] `OBI`: http://obi-ontology.org
- [ ] `NCBITAXON`: https://github.com/obophenotype/ncbitaxon
- [ ] `PATO`: https://github.com/pato-ontology/pato/
- [ ] `OBO`: https://oborel.github.io/
- [ ] `SEPIO`: https://github.com/monarch-initiative/SEPIO-ontology
- [x] `bibo`: http://purl.org/ontology/bibo/
- [ ] `STATO`: https://stato-ontology.org/
- [ ] `IAO`: https://github.com/information-artifact-ontology/IAO/`
- [ ] `UBERON`: http://obophenotype.github.io/uberon/
- [ ] `XCO`: https://www.ebi.ac.uk/ols4/ontologies/xco
- [ ] `RDFS`: https://www.ebi.ac.uk/ols4/ontologies/rdfs
- [ ] `OWL`: https://www.ebi.ac.uk/ols4/ontologies/owl
- [ ] `SRAO`: https://github.com/FAIRsharing/subject-ontology
- [ ] `SNOMED`: https://www.ebi.ac.uk/ols4/ontologies/snomed
- [x] `DPV`: https://w3c.github.io/dpv/dpv
- [ ] `NFO`: https://www.semanticdesktop.org/ontologies/2007/03/22/nfo

**Comment by jsheunis** [comment]
- [ ] `PROV-O`: https://www.w3.org/ns/prov-o

**Comment by mih** [comment]
This will become interesting again in #86, but in principle there will be no default context anymore, hence this issue is obsolete.
