### ISSUE TITLE
Capture metadata on associated projects (dataset is used by)

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-tabby#27]
This is related to a superdataset-subdataset relationship, but could also be interpreted more broadly, when the object of `is_used_by` is not another dataset, but just a description of an (ongoing) activity.

**Comment by jsheunis** [comment]
Feels like this `Role` could be useful here: https://schema.org/Role, as a means of attaching more information to a given relationship/property.

**Comment by jsheunis** [comment]
Related effort to defined the relationship to a datalad subdataset or git submodule: https://github.com/psychoinformatics-de/datalad-tabby/issues/56

**Comment by mih** [comment]
In https://rdm.sfb1451.de/data-catalog-submission/#table-used-for the aim is to have the entities of a `used-for` table to be of type `activity` as defined by PROV-DM.
