### ISSUE TITLE
How to annotate grant funding

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-tabby#28]
The https://schema.org/Dataset object has a https://schema.org/funding property that links any number of https://schema.org/Grant s

For each https://schema.org/Grant (vertical table), we have

- https://schema.org/identifier: The grant identifier
- https://schema.org/funder: as a defined term, such as `DFG` (defined as `https://www.dfg.de`)

**Comment by mslw** [comment]
I agree that identifier and funder seem to be the most relevant.

Grant description *may* also include grant title, url to project database, maybe also funding scheme? I see Grant can also have (from Thing):
- https://schema.org/name
- https://schema.org/description
- https://schema.org/url

[Example 5](https://schema.org/Grant#eg-0470) from schema.org uses name & url.

**Comment by mih** [comment]
See https://rdm.sfb1451.de/data-catalog-submission/#table-funding-required for a concrete example implementation
