### ISSUE TITLE
Helper script to produce `files` sheet from directory

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-tabby#33]
User feedback is calling for this, and it makes a lot of sense.

It would be much simpler for users to get a comprehensive TSV that they can C&P in the right spot -- potentially after removing a few row that are not relevant.

**Comment by jsheunis** [comment]
Seems like `ls-file-collection` would be good for this since it can give path, md5 checksum, size.

Would the steps be as follows?
- user runs python script with path to directory as argument (possibly also another argument to recursive)
- script runs `ls-file-collection` on directory(ies)
- extract useful variables and populate flat list of dictionaries
- convert list to a tabby TSV file

**Comment by christian-monch** [comment]
I think something like this might be the simplest solution (`ls-file-collection directory` needs outside recursion implementation IIUC, `ls-file-collection gitworktree` does not report sizes).  The following command executed in the root of the dataset for which a files-TSV should be created would emit a TSV with file names, empty URLs, and file-sizes.

```
echo -e "from os import stat\nfrom pathlib import Path\nfor p in Path('.').glob('**/'): print(f'{p}\t\t{stat(p).st_size}')"|python -
```

**Comment by christian-monch** [comment]
I think the simplest solution might be (in Linux) to use the following command to generate the file-table (execute it in the root of the dataset for which a table should be generated). The thing is that `ls-file-collection directory` requires external recursion implementation IIUC, and `ls-file-collection gitworktree` does not report sizes. 

```shell
find . -printf "%p\t\t%s\n"
```

There are a few things: the command would only report the size of a link, not of a link target.

**Comment by christian-monch** [comment]
Here without listing the content of `.git`:

```shell
find . -printf "%P\t\t%s\n" -name .git -prune
```

**Comment by christian-monch** [comment]
This is a better `find`-command line because the previous two command lines will emit directory names, and we do not support the entry of directories in file-tables:

```
find . -not -type d -printf "%P\t\t%s\n" -name .git -prune
```

**Comment by jsheunis** [comment]
This will be a script / command in `datalad-tabby` that will have to work for users across OS, so I think something Python and/or datalad-based would be better, even though the `find` example command can be given to linux users as an alternative.

**Comment by jsheunis** [comment]
Is it a more attractive option to create a pure Python script and then package it as an executable?
