### ISSUE TITLE
Doc: rewrite or retire tabby spec 

### ISSUE THREAD

**Issue by mslw** [psychoinformatics-de/datalad-tabby#39]
The "Tabular dataset description" page is still partially valid (e.g. motivations, some key properties), but describes the initial idea for the format (dataset file + files file). This will be partially replaced by #36

**Comment by mih** [comment]
I have moved this file into a hidden toctree. I want to write the actual specification in a way that is agnostic of a particular application or use case. This wrtie-up should turn into an example use case (part of the docs) that shows how the general principle can be applied to a particular domain.
