### ISSUE TITLE
Support no-prefix metadata records (one record per directory)

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-tabby#50]
#48 made me think about multi-record organizations. I think it should be useful to support schemes like

`<root> / <dataset-id> / <dataset-version> / <tabby-collection>`

This would make a common prefix unnecessary. A record would have files like

- `dataset.tsv`
- `authors.tsv`
- `authors.override.json`

and all files of a record (and only those) would be contained in a (versioned) directory.

**Comment by christian-monch** [comment]
I think that is a useful structure

**Comment by christian-monch** [comment]
Does this imply to serialize a dataset tree (git repos with submodules) into a collection of directories, which are structured as described above?

IIUC that would require the possibility for a sub-module entry in a tabby-record. Or did I misunderstand the intention here?
