### ISSUE TITLE
Docs on how to annotate "origin-project" for a dataset

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-tabby#59]
@mslw suggest to go for a plain `isAssociatedWith` and assign a globally unique identifier for a project.

If then, somewhere, this project entity is defined for/with that identifier queries that involve the origin project could be satisfied.

Here is a demo (using a faux definition of `is-associated-with`)

```json
{
  "@context": 
   {
     "Dataset": "https://schema.org/Dataset",
     "ex": "https://example.com/",
     "crc-project": {
        "@id": "ex:is-associated-with",
        "@type": "@vocab",
         "@context": {
           "@vocab": "https://sfb1451.de/"
         }
      }
  },
  "@type": "Dataset",
  "crc-project": "Z03"
}
```

which expands to

```json
{
  "@type": "https://schema.org/Dataset",
  "https://example.com/is-associated-with": {
    "@id": "https://sfb1451.de/Z03"
  }
}
```
[Playground](https://json-ld.org/playground/#startTab=tab-compacted&json-ld=%7B%22%40context%22%3A%7B%22Dataset%22%3A%22https%3A%2F%2Fschema.org%2FDataset%22%2C%22ex%22%3A%22https%3A%2F%2Fexample.com%2F%22%2C%22crc-project%22%3A%7B%22%40id%22%3A%22ex%3Ais-associated-with%22%2C%22%40type%22%3A%22%40vocab%22%2C%22%40context%22%3A%7B%22%40vocab%22%3A%22https%3A%2F%2Fsfb1451.de%2F%22%7D%7D%7D%2C%22%40type%22%3A%22Dataset%22%2C%22crc-project%22%3A%22Z03%22%7D&context=%7B%7D)

This approach generalizes #54 with a property-specific vocabulary definition.

**Comment by mih** [comment]
This issue is now tracked as one aspect of dataset descriptions with `tabby` in https://github.com/psychoinformatics-de/datalad-tabby/issues/102

**Comment by mslw** [comment]
Coming back to this issue (still with half-formed thoughts), https://schema.org/Dataset has author, contributor, and creator properties [^1] - all of which can be Organization or Person.

A https://schema.org/ResearchProject is a specific type of Project, which is a specific type of Organization.

Maybe we can make the crc-project be a ResearchProject (e.g. `{"name": "INF", "alternateName": Data management for computational modelling, "url":"https://sfb1451.de", "memberOf": SFB1451`}, where SFB1451 is also a ResearchProject), and an author / contributor of the dataset?

One potential problem may be with selecting a list of authors (in SFB context we usually only mean people).

[^1]: these are also defined in Dublin Core https://www.dublincore.org/specifications/dublin-core/dcmi-terms/
