### ISSUE TITLE
Develop specification for file-level metadata

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-tabby#6]
And important goal for this is that any file metadata table is (or can be sufficient) input for `addurls` for creation a fully populated dataset.

**Comment by jsheunis** [comment]
- catalog file schema here: https://github.com/datalad/datalad-catalog/blob/main/datalad_catalog/schema/jsonschema_file.json

**Comment by mih** [comment]
This is now replaced by more concrete issue:

- https://github.com/psychoinformatics-de/datalad-tabby/issues/78
- https://github.com/psychoinformatics-de/datalad-tabby/issues/20

https://rdm.sfb1451.de/data-catalog-submission/#table-files has a concrete implementation.
