### ISSUE TITLE
Support multi-sheet spreadsheet input

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-tabby#8]
The native representation of metadata should be something geared towards long-term archival and universal readability, ie. plain-text TSV. However, for editing/entry practice, it makes a lot of sense to use multi-sheet spreadsheets that bind the different tables associated with a dataset together. Google sheets, MS/Libre/Only Office all support that. The latter allows for convenient online editing in nextcloud instances too, offering a suitable workflow on institutional deployments.

**Comment by jsheunis** [comment]
A comment related to supporting multi-sheet input: if we're doing this I think it also makes sense to allow definitions to be located in a separate sheet. While working with the examples, it felt intuitive for me to look in a separate sheet for `dataset`, `files` and `definitions`. Though, i think it still makes sense to allow definitions and dataset metadata to be supplied in a single sheet.

**Comment by mih** [comment]
We merged the necessary low-level tooling with #34 

This idea is to be able to convert to and from multi-sheet XLSX files to aid editing convenience, but to use a collection of plain-text files as the main (and only) native format -- more suitable for long-term archival purposes.
